### ISSUE TITLE
在MIUI14下打开在线曲库时闪退

### ISSUE THREAD

**Issue by suqing114** [weixiansen574/Genshin-Lyre-midi-player#1]
机型:红米k40s
系统版本:14.0.22.12.8dev
报错信息:因应用自身空指针异常，造成闪退
日志
java.lang.NullPointerException: Attempt java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Integer com.alibaba.fastjson.JSONObject.getInteger(java.lang.String)' on a null object reference
	at top.weixiansen574.LyrePlayer.SelecFromServerActivity$6.success(SelecFromServerActivity.java:290)
	at top.weixiansen574.LyrePlayer.util.HttpUtil$1$2.run(HttpUtil.java:68)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
 invoke virtual method 'java.lang.Integer com.alibaba.fastjson.JSONObject.getInteger(java.lang.String)' on a null object reference
	at top.weixiansen574.LyrePlayer.SelecFromServerActivity$6.success(SelecFromServerActivity.java:290)
	at top.weixiansen574.LyrePlayer.util.HttpUtil$1$2.run(HttpUtil.java:68)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by weixiansen574** [comment]
就MIUI14会出问题？其他手机不会？如果真是这样的话用QQ联系我（1695339869）。
